### ISSUE TITLE
Error when opening .czi file

### ISSUE THREAD

**Issue by Maoting-C** [amin-nejat/CELL_ID#10]
Hi,

I got an error when I tried to open a .czi file. The error is as below:
![image](https://github.com/amin-nejat/CELL_ID/assets/78054715/e438c2da-dc64-4839-a5d3-e16db3625ce3)

I am using the Windows OS and the latest NeuroPAL software. The czi file can be open in Zen light and has 4 neuroPAL channels, one GFP reporter channel but no DIC channel. Is the problem with the incompatibility of channel numbers?

Looking forward to the reply.

Thanks!

**Comment by amin-nejat** [comment]
Hi!

Some information that can be helpful:

1. Yemini lab (Prof. Yemini is the main developer of NeuroPAL) is maintaining the software under a different repository (like below), so the first step is to try the other repo and see if it resolves your problem. I'll work with Eviatar to combine the two repositories into one to avoid further confusion.

https://github.com/Yemini-Lab/NeuroPAL_ID

2. Regarding the file format, the manual written by Eviatar (like below) has a section on file formats describing what's necessary to be included in your file. If your file does not follow that format, just create a fake DIC channel with all zeros and re-save your file, and try it again.

https://www.dropbox.com/s/idjkptbwrysj6t1/NeuroPAL%20Software%20Manual%20v1.pdf?dl=0

3. In case the problem still persists, use the function DataHandling.imreadCZI(file_address) to load your file within the Matlab console and debug from there. If the function is able to open your file properly then the software should be able to do so as well. 

Hope this information helps.

Amin
